// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vehvecxeforxrvghhmlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlaHZlY3hlZm9yeHJ2Z2hobWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDA5NzMsImV4cCI6MjA2MzY3Njk3M30.B6q2wDw6_V2TPUS5ENzVLIoQWrKmuKzdH7SDbCDC3Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);